### PR TITLE
Use a page templating system instead of repeated html with minor changes

### PR DESCRIPTION
**Pull request by lungyiing**
Refactored the website to allow for more dynamic page content whilst still retaining the current site content.
- Uses a simple routing system instead of rules.php, modes.php etc.
- Move page markdown files to their own directory
- Reformatted PHP with PHPStorm

### CODE REVIEW

**Comment by lungyiing** [comment]
I'm not sure if the site should be minimal or if some basic bootstrap components should be used. I guess this is up to @md-5

**Comment by lungyiing** [comment]
The commit below adds a small tweak to the way pages are presented

**Comment by joejenniges** [comment]
We already have a dynamic system in the works for the site. We're going to hold off on this. Could you possibly squash your commits though please?

**Comment by md-5** [comment]
Pretty nice, but the site is basically the responsibility of @NickG365 and @GunfighterJ you are best discussing this with them, I don't really want to see your work go unnoticed.

**Comment by lungyiing** [comment]
See https://github.com/SpigotMC/irc/pull/8

**Pull request closed without merging**
